language: node_js

deploy:
  provider: heroku
  api_key:
    secure: TRDuugDVrxVEZ//edRD5nHKCnTjqhRI6MmRStwMujyeNZimvAOIHpvTc+UTT43tr+gMLRh79bXR/8gOBCkEIXiAg8ARtNRsWDHiu/BGDyjEYilxXZXxi7/3CXWQjn5r/kP5lczdhpEEj1XuXVW5uh6gzquukGata+sMz7O4upeaJ/3eigYHpc2sUK87nqLucUJtYcIZqV2X6ykXNFphraMh/wvadu3ecMT/oOxpbyMB0CmeGyGTElwqlZaxAWH057+zu7+J4k443RQkQEnAL64E+qf64UYC8AraUiea4DUatPye9fj1QQdmKCm6W3SQdjK7SVZfmDBxRv8BsigvvW0oH3tfMmLIJvpcNmTIUBjdwCfPtg3dn/06iMMydZQNIp8ol8ju3MP/wGe4vLyLE5mWpjaGZOC0VOSEu59BC8ApvNE4pvIOWUKo/Y1iD7WymODWCf15eoSQtonap/x9ARC4BF5/jQPoQpuyL3jC8vfd+LmZLxEwleSxitIUJ3Rm+hsH7t/2bYAlsOuD3uvKykY3RF/awwsBsPe9i7WVPbhXdi5Rr0ZK++7UtIOQHn5UhB8T0ChsOLhWDSU24MhC4nzs4uyfwSjdhquiIxRUFIMjPZ64kxk52fuox2EpxA5YqaS+JX1r+8J2+OBZabdsim2PpXeThQyjV0wD84waBuHU=
